postgresql: &postgresql
  adapter: postgresql
  host: localhost
  encoding: unicode

development:
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  database: react-rails_dev
  pool: 5
  username: postgres
  password: root

test: &test
  adapter: postgresql
  host: localhost
  port: 5432
  encoding: unicode
  database: react-rails_test
  pool: 5
  username: postgres
  password: root

production:
  username: postgres
  host: <%= ENV["POSTGRESQL_HOST"] || "db" %>
  adapter: postgresql
  encoding: unicode
  database: giasu_prod
  template: template0
  pool: 15

cucumber:
  <<: *test
